name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - "*.*.*"
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
    
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,name=iPhone 16,OS=18.1
          - platform=watchOS Simulator,name=Apple Watch SE (40mm) (2nd generation),OS=11.1
          - platform=tvOS Simulator,name=Apple TV 4K (3rd generation) (at 1080p),OS=18.1
          - platform=macOS,arch=arm64
    with:
      package: "OversizeCore"
      destination: ${{ matrix.destination }}
    secrets: inherit
    
  tests:
     name: Test
     needs: build-swiftpm
     uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
     secrets: inherit

  bump:
    name: Bump version
    needs: tests
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit

  release:
    name: Create Release
    if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/release.yml@main
    secrets: inherit
